[2024-03-11 11:10:57,247]16 root-INFO-Main code is starting
[2024-03-21 11:29:40,645]24 root-INFO-Enter the data ingestion component
[2024-03-21 11:29:40,654]27 root-INFO-Read the dataset as dataframe
[2024-03-21 11:29:40,663]31 root-INFO-Train test split initiated
[2024-03-21 11:29:40,673]36 root-INFO-Ingestion data is completed
[2024-03-21 11:29:40,697]68 root-INFO-Read train and test data completed
[2024-03-21 11:29:40,698]69 root-INFO-Obtaining preprocessing object
[2024-03-21 11:29:40,698]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 11:29:40,698]51 root-INFO-Categorical columns encoding
[2024-03-21 11:29:40,700]91 root-ERROR-An error occurred: "[('writing_score', 'reading_score')] not found in axis"
[2024-03-21 11:31:19,441]24 root-INFO-Enter the data ingestion component
[2024-03-21 11:31:19,449]27 root-INFO-Read the dataset as dataframe
[2024-03-21 11:31:19,457]31 root-INFO-Train test split initiated
[2024-03-21 11:31:19,466]36 root-INFO-Ingestion data is completed
[2024-03-21 11:31:19,488]68 root-INFO-Read train and test data completed
[2024-03-21 11:31:19,488]69 root-INFO-Obtaining preprocessing object
[2024-03-21 11:31:19,488]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 11:31:19,488]51 root-INFO-Categorical columns encoding
[2024-03-21 11:31:19,489]91 root-ERROR-An error occurred: "[('writing_score', 'reading_score')] not found in axis"
[2024-03-21 11:34:06,070]24 root-INFO-Enter the data ingestion component
[2024-03-21 11:34:06,081]27 root-INFO-Read the dataset as dataframe
[2024-03-21 11:34:06,101]31 root-INFO-Train test split initiated
[2024-03-21 11:34:06,112]36 root-INFO-Ingestion data is completed
[2024-03-21 11:34:06,137]68 root-INFO-Read train and test data completed
[2024-03-21 11:34:06,137]69 root-INFO-Obtaining preprocessing object
[2024-03-21 11:34:06,137]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 11:34:06,137]51 root-INFO-Categorical columns encoding
[2024-03-21 11:34:06,138]91 root-ERROR-An error occurred: "[('writing_score', 'reading_score')] not found in axis"
[2024-03-21 11:37:23,945]24 root-INFO-Enter the data ingestion component
[2024-03-21 11:37:23,951]27 root-INFO-Read the dataset as dataframe
[2024-03-21 11:37:23,960]31 root-INFO-Train test split initiated
[2024-03-21 11:37:23,970]36 root-INFO-Ingestion data is completed
[2024-03-21 11:37:23,993]68 root-INFO-Read train and test data completed
[2024-03-21 11:37:23,993]69 root-INFO-Obtaining preprocessing object
[2024-03-21 11:37:23,993]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 11:37:23,993]51 root-INFO-Categorical columns encoding
[2024-03-21 11:37:23,994]91 root-ERROR-An error occurred: "[('writing_score', 'reading_score')] not found in axis"
[2024-03-21 11:37:58,889]24 root-INFO-Enter the data ingestion component
[2024-03-21 11:37:58,895]27 root-INFO-Read the dataset as dataframe
[2024-03-21 11:37:58,902]31 root-INFO-Train test split initiated
[2024-03-21 11:37:58,913]36 root-INFO-Ingestion data is completed
[2024-03-21 11:37:58,935]68 root-INFO-Read train and test data completed
[2024-03-21 11:37:58,936]69 root-INFO-Obtaining preprocessing object
[2024-03-21 11:37:58,936]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 11:37:58,936]51 root-INFO-Categorical columns encoding
[2024-03-21 11:37:58,936]91 root-ERROR-An error occurred: "[('writing_score', 'reading_score')] not found in axis"
[2024-03-21 11:38:30,103]24 root-INFO-Enter the data ingestion component
[2024-03-21 11:38:30,110]27 root-INFO-Read the dataset as dataframe
[2024-03-21 11:38:30,117]31 root-INFO-Train test split initiated
[2024-03-21 11:38:30,129]36 root-INFO-Ingestion data is completed
[2024-03-21 11:38:30,150]68 root-INFO-Read train and test data completed
[2024-03-21 11:38:30,150]69 root-INFO-Obtaining preprocessing object
[2024-03-21 11:38:30,150]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 11:38:30,150]51 root-INFO-Categorical columns encoding
[2024-03-21 12:03:58,940]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:03:58,940]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:03:58,956]31 root-INFO-Train test split initiated
[2024-03-21 12:03:58,956]36 root-INFO-Ingestion data is completed
[2024-03-21 12:03:58,987]68 root-INFO-Read train and test data completed
[2024-03-21 12:03:58,987]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:03:58,987]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:03:58,987]51 root-INFO-Categorical columns encoding
[2024-03-21 12:12:52,160]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:12:52,160]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:12:52,175]31 root-INFO-Train test split initiated
[2024-03-21 12:12:52,175]36 root-INFO-Ingestion data is completed
[2024-03-21 12:12:52,207]68 root-INFO-Read train and test data completed
[2024-03-21 12:12:52,207]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:12:52,207]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:12:52,207]51 root-INFO-Categorical columns encoding
[2024-03-21 12:20:18,388]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:20:18,404]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:20:18,414]31 root-INFO-Train test split initiated
[2024-03-21 12:20:18,422]36 root-INFO-Ingestion data is completed
[2024-03-21 12:20:18,449]68 root-INFO-Read train and test data completed
[2024-03-21 12:20:18,449]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:20:18,449]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:20:18,449]51 root-INFO-Categorical columns encoding
[2024-03-21 12:22:47,100]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:22:47,116]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:22:47,116]31 root-INFO-Train test split initiated
[2024-03-21 12:22:47,131]36 root-INFO-Ingestion data is completed
[2024-03-21 12:22:47,163]68 root-INFO-Read train and test data completed
[2024-03-21 12:22:47,163]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:22:47,163]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:22:47,163]51 root-INFO-Categorical columns encoding
[2024-03-21 12:23:54,967]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:23:54,983]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:23:54,983]31 root-INFO-Train test split initiated
[2024-03-21 12:23:54,998]36 root-INFO-Ingestion data is completed
[2024-03-21 12:23:55,014]68 root-INFO-Read train and test data completed
[2024-03-21 12:23:55,014]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:23:55,014]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:23:55,014]51 root-INFO-Categorical columns encoding
[2024-03-21 12:24:10,616]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:24:10,632]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:24:10,632]31 root-INFO-Train test split initiated
[2024-03-21 12:24:10,647]36 root-INFO-Ingestion data is completed
[2024-03-21 12:24:10,663]68 root-INFO-Read train and test data completed
[2024-03-21 12:24:10,663]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:24:10,663]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:24:10,663]51 root-INFO-Categorical columns encoding
[2024-03-21 12:24:10,679]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:29:24,106]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:29:24,121]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:29:24,121]31 root-INFO-Train test split initiated
[2024-03-21 12:29:24,137]36 root-INFO-Ingestion data is completed
[2024-03-21 12:29:24,168]68 root-INFO-Read train and test data completed
[2024-03-21 12:29:24,168]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:29:24,168]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:29:24,168]51 root-INFO-Categorical columns encoding
[2024-03-21 12:29:24,168]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:29:43,647]24 root-INFO-Enter the data ingestion component
[2024-03-21 12:29:43,647]27 root-INFO-Read the dataset as dataframe
[2024-03-21 12:29:43,662]31 root-INFO-Train test split initiated
[2024-03-21 12:29:43,662]36 root-INFO-Ingestion data is completed
[2024-03-21 12:29:43,693]68 root-INFO-Read train and test data completed
[2024-03-21 12:29:43,693]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:29:43,693]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:29:43,693]51 root-INFO-Categorical columns encoding
[2024-03-21 12:29:43,693]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:39:39,644]25 root-INFO-Enter the data ingestion component
[2024-03-21 12:39:39,660]28 root-INFO-Read the dataset as dataframe
[2024-03-21 12:39:39,660]32 root-INFO-Train test split initiated
[2024-03-21 12:39:39,676]37 root-INFO-Ingestion data is completed
[2024-03-21 12:39:39,707]68 root-INFO-Read train and test data completed
[2024-03-21 12:39:39,707]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:39:39,707]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:39:39,707]51 root-INFO-Categorical columns encoding
[2024-03-21 12:39:39,707]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:42:19,943]25 root-INFO-Enter the data ingestion component
[2024-03-21 12:42:19,943]28 root-INFO-Read the dataset as dataframe
[2024-03-21 12:42:19,943]32 root-INFO-Train test split initiated
[2024-03-21 12:42:19,959]37 root-INFO-Ingestion data is completed
[2024-03-21 12:42:19,974]68 root-INFO-Read train and test data completed
[2024-03-21 12:42:19,974]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:42:19,974]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:42:19,974]51 root-INFO-Categorical columns encoding
[2024-03-21 12:42:19,990]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:43:47,171]25 root-INFO-Enter the data ingestion component
[2024-03-21 12:43:47,171]28 root-INFO-Read the dataset as dataframe
[2024-03-21 12:43:47,171]32 root-INFO-Train test split initiated
[2024-03-21 12:43:47,202]37 root-INFO-Ingestion data is completed
[2024-03-21 12:43:47,218]68 root-INFO-Read train and test data completed
[2024-03-21 12:43:47,218]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:43:47,218]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:43:47,218]51 root-INFO-Categorical columns encoding
[2024-03-21 12:43:47,233]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:50:45,972]25 root-INFO-Enter the data ingestion component
[2024-03-21 12:50:45,972]28 root-INFO-Read the dataset as dataframe
[2024-03-21 12:50:45,988]32 root-INFO-Train test split initiated
[2024-03-21 12:50:45,988]37 root-INFO-Ingestion data is completed
[2024-03-21 12:50:46,019]68 root-INFO-Read train and test data completed
[2024-03-21 12:50:46,019]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:50:46,019]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:50:46,019]51 root-INFO-Categorical columns encoding
[2024-03-21 12:50:46,019]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:52:21,622]25 root-INFO-Enter the data ingestion component
[2024-03-21 12:52:21,622]28 root-INFO-Read the dataset as dataframe
[2024-03-21 12:52:21,622]32 root-INFO-Train test split initiated
[2024-03-21 12:52:21,638]37 root-INFO-Ingestion data is completed
[2024-03-21 12:52:21,669]68 root-INFO-Read train and test data completed
[2024-03-21 12:52:21,669]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:52:21,669]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:52:21,669]51 root-INFO-Categorical columns encoding
[2024-03-21 12:52:21,669]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 12:52:21,685]95 root-ERROR-Error occurred during data transformation: Cannot center sparse matrices: pass `with_mean=False` instead. See docstring for motivation and alternatives.
[2024-03-21 12:58:22,971]25 root-INFO-Enter the data ingestion component
[2024-03-21 12:58:22,971]28 root-INFO-Read the dataset as dataframe
[2024-03-21 12:58:22,987]32 root-INFO-Train test split initiated
[2024-03-21 12:58:22,987]37 root-INFO-Ingestion data is completed
[2024-03-21 12:58:23,018]68 root-INFO-Read train and test data completed
[2024-03-21 12:58:23,018]69 root-INFO-Obtaining preprocessing object
[2024-03-21 12:58:23,018]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 12:58:23,018]51 root-INFO-Categorical columns encoding
[2024-03-21 12:58:23,018]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 13:02:24,298]25 root-INFO-Enter the data ingestion component
[2024-03-21 13:02:24,298]28 root-INFO-Read the dataset as dataframe
[2024-03-21 13:02:24,298]32 root-INFO-Train test split initiated
[2024-03-21 13:02:24,314]37 root-INFO-Ingestion data is completed
[2024-03-21 13:02:24,345]68 root-INFO-Read train and test data completed
[2024-03-21 13:02:24,345]69 root-INFO-Obtaining preprocessing object
[2024-03-21 13:02:24,345]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 13:02:24,345]51 root-INFO-Categorical columns encoding
[2024-03-21 13:02:24,345]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 13:09:13,768]25 root-INFO-Enter the data ingestion component
[2024-03-21 13:09:13,784]28 root-INFO-Read the dataset as dataframe
[2024-03-21 13:09:13,784]32 root-INFO-Train test split initiated
[2024-03-21 13:09:13,799]37 root-INFO-Ingestion data is completed
[2024-03-21 13:09:13,815]68 root-INFO-Read train and test data completed
[2024-03-21 13:09:13,815]69 root-INFO-Obtaining preprocessing object
[2024-03-21 13:09:13,815]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 13:09:13,815]51 root-INFO-Categorical columns encoding
[2024-03-21 13:09:13,831]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-21 13:09:51,430]25 root-INFO-Enter the data ingestion component
[2024-03-21 13:09:51,430]28 root-INFO-Read the dataset as dataframe
[2024-03-21 13:09:51,446]32 root-INFO-Train test split initiated
[2024-03-21 13:09:51,462]37 root-INFO-Ingestion data is completed
[2024-03-21 13:09:51,477]68 root-INFO-Read train and test data completed
[2024-03-21 13:09:51,477]69 root-INFO-Obtaining preprocessing object
[2024-03-21 13:09:51,477]50 root-INFO-Numerical columns standard scaling completed
[2024-03-21 13:09:51,477]51 root-INFO-Categorical columns encoding
[2024-03-21 13:09:51,493]82 root-INFO-Applying preprocessing object on training dataframe and test dataframe
[2024-03-25 10:24:51,831]35 root-INFO-Entered the data ingestion method or component
[2024-03-25 10:24:51,866]38 root-INFO-Read the dataset as dataframe
[2024-03-25 10:24:51,876]44 root-INFO-Train test split initiated
[2024-03-25 10:24:51,905]51 root-INFO-Inmgestion of the data iss completed
[2024-03-25 10:24:51,926]87 root-INFO-Read train and test data completed
[2024-03-25 10:24:51,926]89 root-INFO-Obtaining preprocessing object
[2024-03-25 10:24:51,926]63 root-INFO-Categorical columns: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
[2024-03-25 10:24:51,926]64 root-INFO-Numerical columns: ['writing_score', 'reading_score']
[2024-03-25 10:24:51,936]102 root-INFO-Applying preprocessing object on training dataframe and testing dataframe.
[2024-03-25 10:24:51,966]114 root-INFO-Saved preprocessing object.
[2024-03-25 10:24:51,975]32 root-INFO-Splitting training and test input data
[2024-03-25 10:24:55,516]63 root-INFO-Best found model on both training and testing dataset
[2024-03-25 10:46:38,957]35 root-INFO-Entered the data ingestion method or component
[2024-03-25 10:46:38,973]38 root-INFO-Read the dataset as dataframe
[2024-03-25 10:46:38,989]44 root-INFO-Train test split initiated
[2024-03-25 10:46:39,004]51 root-INFO-Inmgestion of the data iss completed
[2024-03-25 10:46:39,036]87 root-INFO-Read train and test data completed
[2024-03-25 10:46:39,036]89 root-INFO-Obtaining preprocessing object
[2024-03-25 10:46:39,036]63 root-INFO-Categorical columns: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
[2024-03-25 10:46:39,036]64 root-INFO-Numerical columns: ['writing_score', 'reading_score']
[2024-03-25 10:46:39,036]102 root-INFO-Applying preprocessing object on training dataframe and testing dataframe.
[2024-03-25 10:46:39,067]114 root-INFO-Saved preprocessing object.
[2024-03-25 10:46:39,082]32 root-INFO-Splitting training and test input data
[2024-03-25 10:46:42,322]63 root-INFO-Best found model on both training and testing dataset
[2024-03-25 11:17:04,047]96 werkzeug-INFO-[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.11:5000
[2024-03-25 11:17:04,047]96 werkzeug-INFO-[33mPress CTRL+C to quit[0m
[2024-03-25 11:25:12,783]96 werkzeug-INFO-[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.11:5000
[2024-03-25 11:25:12,783]96 werkzeug-INFO-[33mPress CTRL+C to quit[0m
[2024-03-25 11:25:12,799]96 werkzeug-INFO- * Restarting with stat
[2024-03-25 11:25:14,957]96 werkzeug-WARNING- * Debugger is active!
[2024-03-25 11:25:14,957]96 werkzeug-INFO- * Debugger PIN: 928-124-835
[2024-03-25 11:30:52,841]828 app-ERROR-Exception on / [GET]
Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\app.py", line 16, in index
    return render_template('index.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2024-03-25 11:30:52,846]96 werkzeug-INFO-192.168.10.11 - - [25/Mar/2024 11:30:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-03-25 11:30:52,921]96 werkzeug-INFO-192.168.10.11 - - [25/Mar/2024 11:30:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-03-25 11:32:06,944]828 app-ERROR-Exception on / [GET]
Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\app.py", line 16, in index
    return render_template('index.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2024-03-25 11:32:06,948]96 werkzeug-INFO-127.0.0.1 - - [25/Mar/2024 11:32:06] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-03-25 11:32:07,018]96 werkzeug-INFO-127.0.0.1 - - [25/Mar/2024 11:32:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-03-25 11:33:17,144]96 werkzeug-INFO-[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.11:5000
[2024-03-25 11:33:17,144]96 werkzeug-INFO-[33mPress CTRL+C to quit[0m
[2024-03-25 11:33:17,144]96 werkzeug-INFO- * Restarting with stat
[2024-03-25 11:33:19,567]96 werkzeug-WARNING- * Debugger is active!
[2024-03-25 11:33:19,591]96 werkzeug-INFO- * Debugger PIN: 928-124-835
[2024-03-25 11:33:41,437]828 app-ERROR-Exception on / [GET]
Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\app.py", line 16, in index
    return render_template('index.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
[2024-03-25 11:33:41,442]96 werkzeug-INFO-192.168.10.11 - - [25/Mar/2024 11:33:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-03-25 11:45:12,166]96 werkzeug-INFO-[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.11:5000
[2024-03-25 11:45:12,166]96 werkzeug-INFO-[33mPress CTRL+C to quit[0m
[2024-03-25 11:45:12,166]96 werkzeug-INFO- * Restarting with stat
[2024-03-25 11:45:14,377]96 werkzeug-WARNING- * Debugger is active!
[2024-03-25 11:45:14,393]96 werkzeug-INFO- * Debugger PIN: 928-124-835
[2024-03-25 11:45:26,417]96 werkzeug-INFO-192.168.10.11 - - [25/Mar/2024 11:45:26] "GET / HTTP/1.1" 200 -
[2024-03-25 11:48:54,745]96 werkzeug-INFO-192.168.10.11 - - [25/Mar/2024 11:48:54] "GET / HTTP/1.1" 200 -
[2024-03-25 11:55:49,054]96 werkzeug-INFO-127.0.0.1 - - [25/Mar/2024 11:55:49] "GET / HTTP/1.1" 200 -
[2024-03-25 11:56:08,756]96 werkzeug-INFO-127.0.0.1 - - [25/Mar/2024 11:56:08] "GET /predictdata HTTP/1.1" 200 -
[2024-03-25 11:57:00,420]96 werkzeug-INFO-127.0.0.1 - - [25/Mar/2024 11:57:00] "[33mGET /GET%20/predictdata%20HTTP/1.1 HTTP/1.1[0m" 404 -
[2024-03-25 11:59:25,155]96 werkzeug-INFO-127.0.0.1 - - [25/Mar/2024 11:59:25] "GET /predictdata HTTP/1.1" 200 -
[2024-03-25 11:59:31,839]96 werkzeug-INFO-127.0.0.1 - - [25/Mar/2024 11:59:31] "GET /predictdata HTTP/1.1" 200 -
[2024-03-25 12:20:19,361]96 werkzeug-INFO- * Detected change in 'E:\\githubprectiece\\app.py', reloading
[2024-03-25 12:20:19,401]96 werkzeug-INFO- * Detected change in 'E:\\githubprectiece\\app.py', reloading
[2024-03-25 12:20:19,486]96 werkzeug-INFO- * Detected change in 'E:\\githubprectiece\\app.py', reloading
[2024-03-25 12:20:20,306]96 werkzeug-INFO- * Restarting with stat
[2024-03-25 12:20:20,336]96 werkzeug-INFO- * Restarting with stat
[2024-03-25 12:20:20,484]96 werkzeug-INFO- * Restarting with stat
[2024-03-25 12:20:26,648]96 werkzeug-WARNING- * Debugger is active!
[2024-03-25 12:20:26,672]96 werkzeug-WARNING- * Debugger is active!
[2024-03-25 12:20:26,680]96 werkzeug-INFO- * Debugger PIN: 928-124-835
[2024-03-25 12:20:26,696]96 werkzeug-INFO- * Debugger PIN: 928-124-835
[2024-03-25 12:20:26,800]96 werkzeug-WARNING- * Debugger is active!
[2024-03-25 12:20:26,816]96 werkzeug-INFO- * Debugger PIN: 928-124-835
[2024-03-27 08:47:40,245]96 werkzeug-INFO-[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.22:5000
[2024-03-27 08:47:40,245]96 werkzeug-INFO-[33mPress CTRL+C to quit[0m
[2024-03-27 08:51:00,624]96 werkzeug-INFO-[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.22:5000
[2024-03-27 08:51:00,624]96 werkzeug-INFO-[33mPress CTRL+C to quit[0m
[2024-03-27 08:51:00,624]96 werkzeug-INFO- * Restarting with stat
[2024-03-27 08:51:03,332]96 werkzeug-WARNING- * Debugger is active!
[2024-03-27 08:51:03,356]96 werkzeug-INFO- * Debugger PIN: 928-124-835
[2024-03-27 08:51:27,076]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:51:27] "GET / HTTP/1.1" 200 -
[2024-03-27 08:51:27,143]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:51:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2024-03-27 08:52:25,038]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:52:25] "GET /predictdata HTTP/1.1" 200 -
[2024-03-27 08:53:15,096]828 application-ERROR-Exception on /predictdata [POST]
Traceback (most recent call last):
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\application.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: CustomException.__init__() takes 1 positional argument but 3 were given
[2024-03-27 08:53:15,096]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:53:15] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-03-27 08:53:44,700]828 application-ERROR-Exception on /predictdata [POST]
Traceback (most recent call last):
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\application.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: CustomException.__init__() takes 1 positional argument but 3 were given
[2024-03-27 08:53:44,700]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:53:44] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-03-27 08:57:49,772]828 application-ERROR-Exception on /predictdata [POST]
Traceback (most recent call last):
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\application.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: CustomException.__init__() takes 1 positional argument but 3 were given
[2024-03-27 08:57:49,772]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:57:49] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-03-27 08:58:03,371]828 application-ERROR-Exception on /predictdata [POST]
Traceback (most recent call last):
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\application.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: CustomException.__init__() takes 1 positional argument but 3 were given
[2024-03-27 08:58:03,371]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:58:03] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-03-27 08:58:11,662]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 08:58:11] "GET /predictdata HTTP/1.1" 200 -
[2024-03-27 09:09:24,999]828 application-ERROR-Exception on /predictdata [POST]
Traceback (most recent call last):
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\myenv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\application.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\githubprectiece\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: CustomException.__init__() takes 1 positional argument but 3 were given
[2024-03-27 09:09:25,005]96 werkzeug-INFO-192.168.10.22 - - [27/Mar/2024 09:09:25] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
